name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        jdk: [8, 11]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: "${{ matrix.jdk }}"
        distribution: "adopt"

    - uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build
      if: matrix.jdk == 8
      run: mvn clean install --batch-mode -Djdk.version=1.${{ matrix.jdk }}
    - name: Build
      if: matrix.jdk != 8
      run: mvn clean install --batch-mode -Djdk.version=${{ matrix.jdk }}
